from enum import Enum

class ProcessingEnums(Enum):
    CSV =  ".csv"
    JSON = ".json"
    TXT = ".txt"
    PDF = ".pdf"
    DOCX = ".docx"
    XLSX = ".xlsx"
    PPTX = ".pptx"
    JPG = ".jpg"
    PNG = ".png"
    GIF = ".gif"
    MP4 = ".mp4"        
    MOV = ".mov"
    AVI = ".avi"
    MKV = ".mkv"
    WEBM = ".webm"
    MP3 = ".mp3"
    WAV = ".wav"
    FLAC = ".flac"
    OGG = ".ogg"
    ZIP = ".zip"
    RAR = ".rar"
    TAR = ".tar"
    GZ = ".gz"
    TAR_GZ = ".tar.gz"
    TAR_BZ2 = ".tar.bz2"
    TAR_XZ = ".tar.xz"
    TAR_LZ4 = ".tar.lz4"
    