from enum import Enum

class ResponseStatus(Enum):
    SUCCESS = "success"
    ERROR = "error"
    PENDING = "pending"
    NOT_FOUND = "not_found"
    UNAUTHORIZED = "unauthorized"
    FORBIDDEN = "forbidden"
    BAD_REQUEST = "bad_request"
    SERVER_ERROR = "server_error"
    TIMEOUT = "timeout"
    CONFLICT = "conflict"
    FILE_UPLOAD_FAILE = "file_upload_failed"
    CREATED = "created"
    UPDATED = "updated"
    DELETED = "deleted"
    VALIDATION_ERROR = "validation_error"
    RATE_LIMIT_EXCEEDED = "rate_limit_exceeded"
    UpLOAD_ERROR = "upload_error"
    DOWNLOAD_ERROR = "download_error"
    PROCESSING = "processing"
    COMPLETED = "completed"
    CANCELED = "canceled"
    PARTIAL_SUCCESS = "partial_success"
    PARTIAL_FAILURE = "partial_failure"
    NO_CONTENT = "no_content"
    ACCEPTED = "accepted"
    REDIRECT = "redirect"
    NOT_MODIFIED = "not_modified"
    CONFLICTING_REQUEST = "conflicting_request"
    UpLOAD_SUCCESS = "upload_success"
    UpLOAD_FAILED = "upload_failed"
    DOWNLOAD_SUCCESS = "download_success"
    DOWNLOAD_FAILED = "download_failed" 
    PROCESSING_SUCCESS = "processing_success"
    PROCESSING_FAILED = "processing_failed"
    CANCELLED_SUCCESS = "cancelled_success"
    CANCELLED_FAILED = "cancelled_failed"

    PARTIAL_UPLOADED = "partial_uploaded"
    PARTIAL_UPLOADED_FAILED = "partial_uploaded_failed"
    PARTIAL_DOWNLOADED = "partial_downloaded"
    PARTIAL_DOWNLOADED_FAILED = "partial_downloaded_failed"
    PARTIAL_PROCESSED = "partial_processed"
    PARTIAL_PROCESSED_FAILED = "partial_processed_failed"
    PARTIAL_CANCELLED = "partial_cancelled"
    PARTIAL_CANCELLED_FAILED = "partial_cancelled_failed"
    UNKNOWN_ERROR = "unknown_error"
    NO_FILE_ID_ERORR= "no_file_id_error"
    PROJECT_NOT_FOUND = "project_not_found"
    INSERT_INTO_VECTOR_DB_FAILED = "insert_into_vector_db_failed"
    INSERT_INTO_VECTOR_DB_SUCCESS = "insert_into_vector_db_success"
    VECTORDB_COLLECTION_SUCCESS = "vectordb_collection_success"
    VECTORDB_COLLECTION_FAILED = "vectordb_collection_failed"
    VECTOR_DB_SEARCH_ERORR = "vector_db_search_error"
    VECTOR_DB_SEARCH_SUCCESS = "vector_db_search_success"


